module.exports = [
  ...require('./format.js'),
  ...require('./markup.js'),
  ...require('./relAlternate.js'),
  ...require('./typeMismatch.js'),
  ...require('./extSpoofing.js'),
  ...require('./2formats.js'),
  ...require('./3formats.js'),
  ...require('./typeAttribute.js'),
  ...require('./dataUrl.js'),
  ...require('./notFound.js'),
  ...require('./mediaAttribute.js'),
  ...require('./mediaQueries.js'),
  ...require('./lightDark.js'),
  ...require('./typeOctetStream.js'),
];
